export const CREATE_TASK = "CREATE_TASK";
export const CREATE_CLONED_CARDS = "CREATE_CLONED_CARDS";

export const DELETE_CARD = "UPDATE_TASK";
export const CLONE_CARD = "CLONE_CARD";
export const UPDATE_TASK_CONTENT = "UPDATE_TASK_CONTENT";
export const UPDATE_CARD = "UPDATE_TASK_TITLE";
export const DELETE_LIST_CARDS = "DELETE_LIST_CARDS";
export const LOAD_CARDS = "LOAD_CARDS";
