export const CREATE_LIST_TASK = "CREATE_LIST_TASK";
export const CREATE_LIST = "CREATE_LIST";
export const DELETE_LIST = "DELETE_LIST";
export const CLONE_LIST = "CLONE_LIST";
export const UPDATE_LIST_TITLE = "UPDATE_LIST_TITLE";
export const UPDATE_TASK_ORDER = "UPDATE_TASK_ORDER";

export const ADD_CARD_TO_LIST = "ADD_CARD_TO_LIST";
export const REMOVE_CARD_FROM_LIST = "REMOVE_CARD_FROM_LIST";

export const FETCH_LISTS = "FETCH_LISTS";
export const FETCH_LISTS_BEGIN = "FETCH_LISTS_BEGIN";
export const FETCH_LISTS_SUCCESS = "FETCH_LISTS_SUCCESS";

export const LOAD_LISTS = "LOAD_LISTS";
export const CLEAR_LIST = "CLEAR_LIST";
