export const CREATE_TASK = "CREATE_TASK";
export const DELETE_TASK = "UPDATE_TASK";
export const CLONE_TASK = "CLONE_TASK";
export const UPDATE_TASK_CONTENT = "UPDATE_TASK_CONTENT";
export const UPDATE_TASK_TITLE = "UPDATE_TASK_TITLE";
export const UPDATE_TASK_ORDER = "UPDATE_TASK_ORDER";
