export const CREATE_LIST_TASK = "CREATE_LIST_TASK";
export const CREATE_LIST = "CREATE_LIST";
export const DELETE_LIST = "DELETE_LIST";
export const CLONE_LIST = "CLONE_LIST";
export const UPDATE_LIST_TITLE = "UPDATE_LIST_TITLE";
export const UPDATE_TASK_ORDER = "UPDATE_TASK_ORDER";

export const FETCH_LISTS_PENDING = "FETCH_LISTS_PENDING";
export const FETCH_LISTS_SUCCESS = "FETCH_LISTS_SUCCESS";
export const FETCH_LISTS_ERROR = "FETCH_LISTS_ERROR";
