export const SHOW_TASK_MODAL = "SHOW_TASK_MODAL";
export const HIDE_TASK_MODAL = "HIDE_TASK_MODAL";

export const DELETE_BOARD = "DELETE_BOARD";
export const CREATE_BOARD = "CREATE_BOARD";
export const UPDATE_BOARD_TITLE = "UPDATE_BOARD_TITLE";
